apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- cache-purge-job.yaml

images:
- name: image_name
  newName: ghcr.io/scubbo/blog-content
  newTag: 35b9645d6dc0abf458e5e958918c4d0c2bff63c8
