apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- cache-purge-job.yaml

images:
- name: image_name
  newName: ghcr.io/scubbo/blog-content
  newTag: a3b6b4dda3ef2e8262b17f665a9ccf70f073abb3
