apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- cache-purge-job.yaml

images:
- name: image_name
  newName: ghcr.io/scubbo/blog-content
  newTag: c7c9d299a5b0b9d1ab3dfd27526b51e0495a8970
