apiVersion: v1
kind: Service
metadata:
  name: blog-svc-cip
  namespace: blog
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
  sessionAffinity: None
  type: ClusterIP